DROP DATABASE IF EXISTS `spring_boot_chapter7`;
CREATE DATABASE `spring_boot_chapter7` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_BIN;
USE `spring_boot_chapter7`;
CREATE TABLE `t_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) COLLATE UTF8MB4_BIN DEFAULT NULL,
  `note` VARCHAR(255) COLLATE UTF8MB4_BIN DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_BIN;